### ISSUE TITLE
no matches for kind "MqttBridgeConnector" in version "mq.iotoperations.azure.com/v1beta1"

### ISSUE THREAD

**Issue by dguptaSAS** [microsoft/azure_arc#2738] opened 2024-10-02 12:33 UTC
am going through the steps for Azure Jumpstart: [https://azurearcjumpstart.com/azure_arc_jumpstart/azure_edge_iot_ops/aio_manufacturing]

and during the **post-deployment** step, I am getting the following error

resource mapping not found for name: "my-topic-map" namespace: "azure-iot-operations" from "/home/SIJ/Tools/mq_cloudConnector.yml": no matches for kind "MqttBridgeTopicMap" in version "mq.iotoperations.azure.com/v1beta1"
ensure CRDs are installed first
resource mapping not found for name: "my-mqtt-bridge" namespace: "azure-iot-operations" from "/home/SIJ/Tools/mq_cloudConnector.yml": no matches for kind "MqttBridgeConnector" in version "mq.iotoperations.azure.com/v1beta1"
ensure CRDs are installed first
Error from server (NotFound): namespaces "azure-iot-operations" not found
[12:05:02] INFO: Waiting for MQTT services to initialize and the service IP address to be assigned... Waiting for 20 seconds
Error from server (NotFound): namespaces "azure-iot-operations" not found
[12:05:02] INFO: Waiting for MQTT services to initialize and the service IP address to be assigned... Waiting for 20 seconds

the file that is giving the error is [https://github.com/microsoft/azure_arc/blob/main/azure_edge_iot_ops_jumpstart/aio_manufacturing/bicep/artifacts/Settings/mq_cloudConnector.yml]

**Comment by mrhoads** [comment] 2024-10-02 15:39
Hi @dguptaSAS - I'm investigating this.  It looks like the azure-iot-operations extension isn't properly installed, which I suspect may be related to [this issue](https://github.com/microsoft/azure_arc/issues/2731).

**Comment by mrhoads** [comment] 2024-10-02 19:48
I confirmed that this is a result of the same underlying issue that #2731 addresses.  AIO never gets deployed because the extension doesn't get installed.  We're working on a fix.

**Comment by dguptaSAS** [comment] 2024-10-02 20:33
I agree with you [@mrhoards ](https://github.com/mrhoads). this one is related to [#2731](https://github.com/microsoft/azure_arc/issues/2731). The error mentioned in #2731 occurs exactly 3 times before eventually ending up with the mq_cloudconnector issue. But in between it successfully configures the firewall for MQTT Broker and creates the local path provisioner. And eventually ends up in the indefinite loop of 

Error from server (NotFound): namespaces "azure-iot-operations" not found
[12:05:02] INFO: Waiting for MQTT services to initialize and the service IP address to be assigned... Waiting for 20 seconds

**Comment by dguptaSAS** [comment] 2024-10-04 08:17
@mrhoads Furthermore on this. I tried deploying two versions and here are my findings. 

With version, **v0.5.1b1**, _azure it ops_ is not deployed due to the known 'AccessTokenInfo' error. basically issue [#2731](https://github.com/microsoft/azure_arc/issues/2731)
With version, **v0.6.4**,   _azure it ops_ gets deployed but gives the MQ Bridge (coming from mq_cloudConnector.yaml) error as mentioned in the issue.

**Comment by mrhoads** [comment] 2024-10-04 18:11
Thanks for the additional info.  This should be fixed shortly with a PR where we patch the 0.5.1b1 version of the azure-iot-ops extension

**Comment by mrhoads** [comment] 2024-10-04 19:49
@dguptaSAS - this should be fixed with [this PR](https://github.com/microsoft/azure_arc/pull/2742).  Would you please try re-deploying?

**Comment by dguptaSAS** [comment] 2024-10-07 08:31
@mrhoads It is working now. Thanks for the quick fix.

**Closed** 2024-10-07 13:33 UTC
Labels: triage
