### ISSUE TITLE
Logon scripts on ARCBoxClient machine fail!

### ISSUE THREAD

**Issue by DanieleM69** [microsoft/azure_arc#2845] opened 2024-11-12 15:49 UTC
> **Note:** For ease of issues and pull requests management and tracking, we kindly ask you to provide a meaningful and concise title to this issue and answer all questions to the best of your ability.

**Is your issue related to a Jumpstart scenario, ArcBox, HCIBox, or Agora?**
The problem is related to ArcBox for IT Pro scenario.

**Describe the issue or the bug**
The Logon scripts unable to complete because the environment parameters (Tenant, resource group etc.) non correctly passed to the PowerShell scripts! 

**To Reproduce**
The deployment was executed using the ARM Template across multiple regions ("East US, France Central") and produced same results. It was also tested on different subscriptions: Microsoft on Internal and External Tenant.

The PowerShell Logon scripts unable to complete the expected scenario:
- SQL Server VM is only the VM deployed on Hyper-V Server
- No Other VW are deployed
- No Onboarding of Arc Enabled Server
- the last action is deploying SQL Server VM

**Expected behavior**

**Environment summary**

**Have you looked at the Troubleshooting and Logs section?**
No relevant Troubleshooting I can find

**Screenshots**

**Additional context**

**Comment by dkirby-ms** [comment] 2024-11-15 01:33
Can you share your parameters please, without including any secrets?

**Comment by DanieleM69** [comment] 2024-11-16 10:10
sure...

I used the default parameters
the tenant is "CONTOSO" ..... see the Subscription


[cid:cd045e55-6e55-449d-ab43-61845f962c5b]
[cid:e6ada8e9-944c-4e5f-a05c-2e8e8178359a]
[cid:3218812e-2949-491c-b02e-395d6e96c25b]

let me know if you have any questions or concerns

Daniele

________________________________
Da: Dale Kirby ***@***.***>
Inviato: venerdì 15 novembre 2024 02:34
A: microsoft/azure_arc ***@***.***>
Cc: DanieleM69 ***@***.***>; Author ***@***.***>
Oggetto: Re: [microsoft/azure_arc] Logon scripts on ARCBoxClient machine fail! (Issue #2845)


Can you share your parameters please, without including any secrets?

**Comment by yveskerwyn** [comment] 2024-11-19 10:05
Same here

**Comment by janegilring** [comment] 2024-12-04 18:33
@yveskerwyn  @DanieleM69 Did you specify the `namingPrefix` parameter or was that set to the default value?

**Comment by janegilring** [comment] 2024-12-10 17:18
@yveskerwyn @DanieleM69 Any updates from your end?

**Comment by janegilring** [comment] 2024-12-16 20:45
Closing for now, feel free to re-open if you have any updates and the issue is still present.

**Closed by janegilring** 2024-12-16 20:45 UTC
Labels: ArcBox

**Comment by janegilring** [comment] 2024-12-22 21:44
If you were using the `namingPrefix` parameter, we have resolved an issue related to that which was merged today:
https://github.com/microsoft/azure_arc/pull/2887

**Comment by yveskerwyn** [comment] 2024-12-23 17:35
[like]  Yves Kerwyn reacted to your message:
________________________________
