### ISSUE TITLE
AKS on Azure Stack HCI PowerShell

### ISSUE THREAD

**Issue by frteles** [microsoft/azure_arc#479] opened 2021-03-30 10:07 UTC
**Scenario which you are working on**
https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_k8s/aks_stack_hci/aks_hci_powershell/

**Describe the bug**
I've followed the tutorial and was able to get it working. Just have some feedback to provide on ways to improve it and share some issues I've came across

1. I was using a Nested Virtualized environment for this demo. It's not clear in the tutorial, where we should run the commands. I actually started running in the WAC, and after some time, figured it out that it is supposed to be on the Hyper-V host directly. It could be great to clarify this point in the tutorial

2. For the service principal creation, since it's being saved in the variable $sp, it won't provide any output. So probably doesn't make sense to have "This command will return a secure string as shown below:" 

3. Still regarding service principal creation, I think it's important to state that the user we'll use to connect to Azure should have permissions to create service principals in AAD

4. The hyperlink for downloading the AKS-HCI files isn't working, because of a comma at the end of the hyperlink

5. After downloading and extracting the files, I wasn't able to import the modules in the way described in the tutorial. However, I followed this [documentation](https://docs.microsoft.com/en-us/azure-stack/aks-hci/setup-powershell#download-and-install-the-akshci-powershell-module) which suggests the extracting of the files to %systemdrive%\program files\windowspowershell\modules, and then importing them. It worked this way!

6. For the AksHci deployment, the Initialize-AksHciNode, if ran for the first time, will install WinRM which means that a reboot is needed. In that sense, the SP secret stored in a variable will be lost. It could be interesting to mention to save this secret on the PS file, before running the Initialize-AksHciNode command. 

7. During the installation of AksHci I had this error described in our [documentation](https://docs.microsoft.com/en-us/azure-stack/aks-hci/troubleshoot-known-issues#install-akshci-timed-out-with-an-error) for "waiting for API server". That documentation points for a DNS server address misconfiguration in the MocConfig. In order to make sure, I was specifying the DNS server, I changed the command:

$vnet = New-AksHciNetworkSetting -vnetName $vnetName -vipPoolStart $vipPoolStart -vipPoolEnd $vipPoolEnd

for 

$vnet = New-AksHciNetworkSetting -vnetName "InternalSwitch" -k8sNodeIpPoolStart "192.168.1.200" -k8sNodeIpPoolEnd "192.168.1.255" -vipPoolStart "192.168.1.0" -vipPoolEnd "192.168.1.199" -ipAddressPrefix "192.168.1.0/24" -gateway "192.168.1.1" -dnsServers "192.168.1.254"

which is described in our [documentation ](https://docs.microsoft.com/en-us/azure-stack/aks-hci/setup-powershell#step-2-create-a-virtual-network)as well.

After this change, I was able to install successfully and having AKS running in HCI! Not sure if this was only an issue on my side (or do to the NV environment), but I noticed as well some differences in the PS outputs, because I was using the most recent version of AksHci

**Expected behavior**
NA

**Screenshots**
NA

**Additional context**
Keep bringing more scenarios! :)

**Comment by lanicolas** [comment] 2021-03-31 08:25
Hi @frteles thanks for testing the scenario. 

I'll update to the new version of the HCI modules and I have changed the SP notes as well as fixed the link, thanks!. As far as the network configuration goes, I was not able to reproduce the issue, the scenario uses a DHCP based configuration and the command you shared is for a Static config, the error  from our documentation also points out to clusters using static IP addresses. Could it be possible you used a static IP address cluster?

**Comment by frteles** [comment] 2021-04-05 15:47
Hi @lanicolas, 

Not sure, I need to double check on my side, but it might explain the differences, yes. 

Francisco

**Comment by lanicolas** [comment] 2021-04-12 07:39
Hi @frteles 

I'll update the scenario with your recomedations as well as the new cmdlet version, thanks!. If you get the same issue with an static IP cluster please let us know and we can revist, closing the issue for now.

**Closed by lanicolas** 2021-04-12 07:39 UTC
Labels: bug
