### ISSUE TITLE
Can't see SQL Databases using ARC box for it Pros

### ISSUE THREAD

**Issue by carloslone** [microsoft/azure_arc#2782] opened 2024-10-23 23:03 UTC
> **Note:** For ease of issues and pull requests management and tracking, we kindly ask you to provide a meaningful and concise title to this issue and answer all questions to the best of your ability.

**Is your issue related to a Jumpstart scenario, ArcBox, HCIBox, or Agora?**
ArcBox

**Describe the issue or the bug**
after deploying al the infrastructure, when selecting ARCbox SQL machine, and then select databases the databases available in the sql instance are not showing up. 

**To Reproduce**

1. Go to Arcbox SQL VM
2. Click on sql configuration and select Arcbox-sql
3. Scroll down to Databases
4. No databases displayed

**Expected behavior**
get the list of the available databases of the sql instance

**Environment summary**
I have tried deploying with both Developer and Enterprise edition for the SQL Database Edition. The same error happens

**Screenshots**
![Image](https://github.com/user-attachments/assets/7ffd62d6-cd89-48e3-b17b-ff5819285d1f)

**Comment by janegilring** [comment] 2024-10-24 03:33
Hi @carloslone ,

Could you share the logs under `C:\ArcBox\Logs` ?

When we get those we can have a look at what might have happened to the databases.

**Comment by janegilring** [comment] 2024-10-31 05:24
@carloslone Any updates from your side?

**Comment by carloslone** [comment] 2024-10-31 17:40
[LogsBundle-1rpw0z.zip](https://github.com/user-attachments/files/17591301/LogsBundle-1rpw0z.zip)

![Image](https://github.com/user-attachments/assets/3e4ec7e2-2f59-4020-b7e8-2dd9cb54b3c5)

![Image](https://github.com/user-attachments/assets/e206262f-9347-458c-8537-d9dfad3b97c6)

Find the information attached. Just redeployed the IT pro Jumpstart ArcBox

**Comment by janegilring** [comment] 2024-10-31 19:39
@carloslone Thank you. Looking at the log-files I did not see any errors in the section which configured the SQL VM.

Could you logon to the ArcBox-SQL VM, open SQL Management Studio from the desktop and check if you can see these databases?

![Image](https://github.com/user-attachments/assets/371e5878-3bcb-41fd-a4db-985e6db00137)

Based on the outcome, we can check whether to troubleshoot on the SQL- or the Arc-side of things.

**Comment by carloslone** [comment] 2024-10-31 21:05
Databases are there, the problem is that dbs are not reflecting on the Azure Portal as the image shared previously.

**Comment by janegilring** [comment] 2024-11-01 03:29
@carloslone Thanks. It turns out there might be issues on the portal-side. Could you try this Azure Resource Graph Query?

```
resources
| where type =~ 'Microsoft.AzureArcData/sqlServerInstances/databases'
| project name, id
```

alternatively this Azure PowerShell command:

```powershell
Get-AzResource -ResourceType "Microsoft.AzureArcData/sqlServerInstances/databases" | Select-Object Name, ResourceGroupName, Location
```

**Comment by janegilring** [comment] 2024-11-07 08:23
@carloslone Closing this one after our Teams-conversation where you confirmed the databases is showing via ARG/PowerShell. In addition, they have started to show in the portal - so likely something has changed on the service-side or the portal-side.

**Closed by janegilring** 2024-11-07 08:23 UTC
Labels: ArcBox
