### ISSUE TITLE
Azure Arc enabled data services for EKS: Failed to load state error

### ISSUE THREAD

**Issue by dineshkvp** [microsoft/azure_arc#699] opened 2021-08-02 14:00 UTC
https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_data/eks/eks_mssql_mi/

I am trying to setup Azure Arc enabled data services for Amazon Elastic Kubernetes Service and SQL Managed Instance using Terraform through the referenced jump start tutorial (azure_arc\azure_arc_data_jumpstart\eks\mssql_mi\terraform)

After setting up the required TF_VAR variables i ran the Terraform scripts as per the documentation. It created the EKS cluster with two nodes and the windows client instance VMs. But the scripts stopped throwing the below error

"Failed to load state: Failed to read state file: The state file could not be read: read terraform.tfstate: The process cannot access the file because another process has locked a portion of the file"

Even after destroying the environment and setting up the environment again the same error appears. The screenshot is attched. Please guide in resolving this issue.
![ArcDataServiceError](https://user-images.githubusercontent.com/5206595/127873618-e01251f5-ccde-4a4f-8f16-2996d0691753.png)

**Comment by dkirby-ms** [comment] 2021-08-02 14:07
This looks more like an issue with terraform state locking and not specific to the Azure Arc scenario. Please make sure when you destroy your environment all terraform state files are removed (for example by completely deleting the terraform folder).

See below link for more info on terraform state locks.

https://www.terraform.io/docs/language/state/locking.html

**Comment by mdrakiburrahman** [comment] 2021-08-02 14:22
@dineshkvp - I ran into the same issue on Windows, the problem is with how Powershell operates against TF. Once I tried using Bash (WSL using Ubuntu) - it works.

Note that there was a new release of EKS Data Services that just got merged this morning - please refresh from `main` and try using that: https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_data/eks/eks_postgres_hs_terraform/

**Comment by mdrakiburrahman** [comment] 2021-08-02 22:56
@dineshkvp - I have just reproduced the same error with Powershell - it happens at [this line](https://github.com/microsoft/azure_arc/blob/f278e38339ef0e8490a61402eef3877b555c2117/azure_arc_data_jumpstart/eks/terraform/client_vm.tf#L75). It seems like the `local-exec` implements `cmd` - which tries to read from the Terraform State file. You can see others running into this issue [here](https://github.com/hashicorp/terraform/issues/18000) with Terraform as well.

As a workaround on a windows machine, you can [easily install Ubuntu](https://www.microsoft.com/en-us/p/ubuntu/9nblggh4msv6#activetab=pivot:overviewtab) and run Bash - I've verified this error doesn't happen with TF on Bash.

Since this isn't Arc specific, and the workaround above is feasible for Windows users - closing this issue.

**Closed by mdrakiburrahman** 2021-08-02 22:56 UTC
Labels: bug

**Comment by dineshkvp** [comment] 2021-08-05 13:00
@mdrakiburrahman  thanks for the message. I could try from Ubutu subsystem and Terraform scripts completed the provisioning.
