### ISSUE TITLE
azure arc app service - aws eks classic lb

### ISSUE THREAD

**Issue by katomel4** [microsoft/azure_arc#776] opened 2021-09-27 18:52 UTC
please provide document deploy on aws eks.
the default to eks is elb and not nlb. therefore it is not possible to attach ellastic-ip

adding to script configure the elastic ip but do not resolve the elb to nlb:
--configuration-settings "service.beta.kubernetes.io/aws-load-balancer-type=nlb" \
--configuration-settings "envoy.annotations.service.beta.kubernetes.io/aws-load-balancer-eip-allocations=eipalloc-0670afed82551600d" \

or
--configuration-settings "envoy.annotations.service.beta.kubernetes.io/aws-load-balancer-type=nlb" \
--configuration-settings "envoy.annotations.service.beta.kubernetes.io/aws-load-balancer-eip-allocations=eipalloc-0670afed82551600d" \

install script:
az k8s-extension create \
    --resource-group omerk8sarcrg \
    --name $extensionName \
    --cluster-type connectedClusters \
    --cluster-name omereks \
    --extension-type 'Microsoft.Web.Appservice' \
    --release-train stable \
    --auto-upgrade-minor-version true \
    --scope cluster \
    --release-namespace $namespace \
    --configuration-settings "Microsoft.CustomLocation.ServiceAccount=default" \
    --configuration-settings "appsNamespace=${namespace}" \
    --configuration-settings "clusterName=${kubeEnvironmentName}" \
    --configuration-settings "loadBalancerIp=44.193.173.xxx" \
    --configuration-settings "keda.enabled=true" \
    --configuration-settings "buildService.storageClassName=default" \
    --configuration-settings "buildService.storageAccessMode=ReadWriteOnce" \
    --configuration-settings "customConfigMap=${namespace}/kube-environment-config" \
    **--configuration-settings "service.beta.kubernetes.io/aws-load-balancer-type=nlb" \
    --configuration-settings "envoy.annotations.service.beta.kubernetes.io/aws-load-balancer-eip-allocations=eipalloc-0670afed82551600d" \**
    --configuration-settings "logProcessor.appLogs.destination=log-analytics" \
    --configuration-protected-settings "logProcessor.appLogs.logAnalyticsConfig.customerId=xxxxxxxxx" \
    --configuration-protected-settings "logProcessor.appLogs.logAnalyticsConfig.sharedKey=xxxxxxxxxx"

loadbalancer service error:
**service-controller  Error syncing load balancer: failed to ensure load balancer: LoadBalancerIP cannot be specified for AWS ELB**

loadbalancer service describe:
Type:                     LoadBalancer
IP Family Policy:         SingleStack
IP Families:              IPv4
IP:                       10.100.225.132
IPs:                      10.100.225.132
**IP:                       44.193.173.xxx**
Port:                     http  80/TCP

**Comment by likamrat** [comment] 2021-09-27 18:56
@katomel4 please use the ["Feature Request" template](https://github.com/microsoft/azure_arc/issues/new?assignees=&labels=&template=feature_request.md&title=) for this one. Since this is not a bug, I will go ahead and close this for now.

<img width="1091" alt="SNAG-1225" src="https://user-images.githubusercontent.com/46730876/134968308-75ddd843-2db1-48bd-a462-e3ac556aeb1e.png">

**Closed by likamrat** 2021-09-27 18:56 UTC
Labels: bug, triage

**Comment by katomel4** [comment] 2021-09-27 18:59
it is a bug

report error although configured to use AWS NLB 

adding to script configure the elastic ip but do not resolve the elb to nlb:
--configuration-settings "service.beta.kubernetes.io/aws-load-balancer-type=nlb"
--configuration-settings "envoy.annotations.service.beta.kubernetes.io/aws-load-balancer-eip-allocations=eipalloc-0670afed82551600d" \

or
--configuration-settings "envoy.annotations.service.beta.kubernetes.io/aws-load-balancer-type=nlb"
--configuration-settings "envoy.annotations.service.beta.kubernetes.io/aws-load-balancer-eip-allocations=eipalloc-0670afed82551600d" \

**Comment by likamrat** [comment] 2021-09-27 19:02
@katomel4 we consider this a bug if that would have been part of an existing Jumpstart scenario. Since Azure Arc-enabled app services is still in preview and do not officially support EKS, we can put such a scenario in our backlog.
