### ISSUE TITLE
VMware Linux scale Deployment

### ISSUE THREAD

**Issue by Inttruder** [microsoft/azure_arc#525] opened 2021-04-23 21:08 UTC
**Scenario which you are working on**
Deploy CentOS and RHEL VMs at scale with VMware

https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_servers/scaled_deployment/vmware_scaled_powercli_linux/

**Describe the bug**
We have been testing deploying Linux vms using the scaled deployment for Linux. We were able to deploy windows vms(Using the windows steps) and Ubuntu vms(Ubuntu took a minor change to the bash line) using the scaled deployment steps. When we try to run it with CentOS or RHEL we get an error about not being able to find the PowerShell interpreter. We updated to the latest version of Open VM Tools and added the our admin user to the super user group but still get the same error.

I was able to successfully deploy the agent by stopping the scale_deploy script after the file copy then logging into a target vm and running the bash command locally. When we try to have it run through all the servers in the VMware folder is when we get the error.

**To Reproduce**
Follow the steps in the Azure Arc jumpstart for scaled deployment of Linux on VMware in the link above and try to run the script against CentOS or RHEL vms installed into a VMware folder. We were testing this using CentoOS 7.9 and RHEL 8.3 on vSphere 6.7.

**Screenshots**
![PowerShellError](https://user-images.githubusercontent.com/5447086/115926980-929fc480-a438-11eb-9473-d89dca9209e8.JPG)

**Comment by likamrat** [comment] 2021-04-23 23:56
Thank you @Inttruder 
1. "Ubuntu took a minor change to the bash line" can you share more on this?
2. I will try to reproduce. Can you confirm if you have _sudo_ installed on these VMs? the script has a dependency on it as you can see [here](https://github.com/microsoft/azure_arc/blob/main/azure_arc_servers_jumpstart/vmware/scaled_deployment/powercli/linux/scale_deploy.ps1#L37)
3. Can you please try to add replace line 37 with this? It has the _-ScriptType bash_ flag.
_$Result = Invoke-VMScript -VM $VM -ScriptType bash -ScriptText "sudo bash /tmp/arctemp/install_arc_agent.sh" -GuestUser $env:OSAdmin -GuestPassword $env:OSAdminPassword_

**Comment by Inttruder** [comment] 2021-04-26 20:19
Thanks for taking a look at this. Answers inline below. Let me know if you have any other questions.

________________________________
From: Lior Kamrat ***@***.***>
Sent: Friday, April 23, 2021 4:56 PM
To: microsoft/azure_arc ***@***.***>
Cc: Lee Talbert ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [microsoft/azure_arc] VMware Linux scale Deployment (#525)


Thank you @Inttruder<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FInttruder&data=04%7C01%7Clee.talbert%40avanade.com%7C98cd2bf9eb794d0f28f108d906b3756b%7Ccf36141cddd745a7b073111f66d0b30c%7C0%7C0%7C637548190125568758%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=wIxzD5rs7W0BD%2F4cU8ITHI0VmqfktX2VdFp1PMmSlNY%3D&reserved=0>

  1.  "Ubuntu took a minor change to the bash line" can you share more on this? We changed the line to the one below and that seemed to work for Ubuntu.
     *   $Result = Invoke-VMScript -VM $VM -ScriptText "echo $env:OSAdminPassword | sudo -S bash /tmp/arctemp/install_arc_agent.sh" -GuestUser $env:OSAdmin -GuestPassword $env:OSAdminPassword
  2.  I will try to reproduce. Can you confirm if you have sudo installed on these VMs? the script has a dependency on it as you can see here We do have sudo installed on the VMs.
<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fazure_arc%2Fblob%2Fmain%2Fazure_arc_servers_jumpstart%2Fvmware%2Fscaled_deployment%2Fpowercli%2Flinux%2Fscale_deploy.ps1%23L37&data=04%7C01%7Clee.talbert%40avanade.com%7C98cd2bf9eb794d0f28f108d906b3756b%7Ccf36141cddd745a7b073111f66d0b30c%7C0%7C0%7C637548190125578754%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ZNML%2BGHbcAezIPmlCGJQIogMaESZCDvqTBwjqsQn%2F3M%3D&reserved=0>
  3.  Can you please try to add replace line 37 with this? It has the -ScriptType bash flag. I have tried using the -ScriptType Bash flag. I tried it again using your line below and I still get the same error.
$Result = Invoke-VMScript -VM $VM -ScriptType bash -ScriptText "sudo bash /tmp/arctemp/install_arc_agent.sh" -GuestUser $env:OSAdmin -GuestPassword $env:OSAdminPassword

**Comment by likamrat** [comment] 2021-04-26 21:24
@Inttruder can you please reply here?

**Comment by Inttruder** [comment] 2021-04-26 21:37
1. Ubuntu took a minor change to the bash line" can you share more on this?
_We had to change line 37 to the following for Ubuntu.
$Result = Invoke-VMScript -VM $VM -ScriptText "echo $env:OSAdminPassword | sudo -S bash /tmp/arctemp/install_arc_agent.sh" -GuestUser $env:OSAdmin -GuestPassword $env:OSAdminPassword_

2. I will try to reproduce. Can you confirm if you have sudo installed on these VMs? the script has a dependency on it as you can see here. _We do have sudo installed on the VMs._
3. Can you please try to add replace line 37 with this? It has the -ScriptType bash flag.
$Result = Invoke-VMScript -VM $VM -ScriptType bash -ScriptText "sudo bash /tmp/arctemp/install_arc_agent.sh" -GuestUser $env:OSAdmin -GuestPassword $env:OSAdminPassword.  _I have tried using the -ScriptType Bash flag. I tried it again using the line you provided and I still get the same error._

**Comment by likamrat** [comment] 2021-04-26 23:29
I wasn't able to repro on Ubuntu but I did observe few things:
1. No change was needed on the PowerCLI script.
2. sudo user must be configured as passwordless user (will update prereq).
3. Since _wget_ is not always present on CentOS/RHEL i tested it with _curl_. Do you mind replacing line 7 [here](https://github.com/microsoft/azure_arc/blob/main/azure_arc_servers_jumpstart/vmware/scaled_deployment/powercli/linux/install_arc_agent.sh#L7) with this and try again?
_curl -L https://aka.ms/azcmagent -o /tmp/arctemp/install_linux_azcmagent.sh -create-dirs_

**Comment by Inttruder** [comment] 2021-04-27 15:49
Is there anything else I need to change to make the script work with a passwordless user? If I just leave the password blank in the vars file I get an authentication error.

**Comment by likamrat** [comment] 2021-04-27 15:53
See this:
https://serverfault.com/questions/160581/how-to-setup-passwordless-sudo-on-linux

The script is working. See my #3 in my previous comment, once you will verify I will merge the changes.

**Comment by Inttruder** [comment] 2021-04-27 20:37
I did do the change you have above in #3. However, I am erroring out before I get to that line. When I run the script now I get an error on the file copy line about not being able to authenticate. I have the users setup to be passwordless and can change to that use without a password. I have been leaving the password empty in the vars file. Is there something else I need to do to get the passwordless user to work?

**Comment by likamrat** [comment] 2021-04-27 20:59
_passwordless_ means _sudo_ user don't have to enter password every time it's needed for sudo actions, it does not mean you shouldn't still have the password configured. 

For example, in the _vars.ps1_ file you should have something like that, where "arcdemo" is a sudo user. 

```powershell
$env:OSAdmin = 'arcdemo'
$env:OSAdminPassword = 'ArcDemo123!!'
```

**Comment by Inttruder** [comment] 2021-04-29 02:16
I did try it again with the change to the install_arc_agent script using the curl line you mentioned and the passwordless user and I am back to the original PowerShell script interpreter error for CentOS and RHEL.

**Comment by likamrat** [comment] 2021-04-29 13:47
@Inttruder I am unable to reproduce the issue and everything is working as expected on my end. 

* What type of vSphere permissions do you have? 
* Can you please share your script here?
* Can you verify VMware Tools are running on the VM?
* Can you please share the output on your PowerCLI version?
```powershell
Get-Module -Name VMware.PowerCLI | Select-Object -Property Name,Version
```

**Comment by Inttruder** [comment] 2021-04-29 23:14
What type of vSphere permissions do you have? Administrator
Can you please share your script here?
# Define Variables
# Connet to VMware vCenter
Invoke-Expression ".\vars.ps1"
Set-PowerCLIConfiguration -InvalidCertificateAction Ignore -Confirm:$false
Connect-VIServer -Server $env:vCenterAddress -User $env:vCenterUser -Password $env:vCenterUserPassword -Force # vars are defined in vars.ps1
$VMs = Get-Folder -Name $env:VMFolder | Get-VM # VMFolder is defined in vars.ps1

ForEach ($VMName in $VMs) {
  $VM = Get-VM $VMName

  $File1 = "vars.sh" # vars.sh is auto-generated
  $sCopy1 = @{
    Source = $env:SrcPath + $File1 # SrcPath defined in vars.ps1
    Destination = "/tmp/arctemp/"
    VM = $VM
    LocalToGuest = $true
    GuestUser = "$env:OSAdmin" # OSAdmin defined in vars.ps1
    GuestPassword = "$env:OSAdminPassword" # OSAdminPassword defined in vars.ps1
    Verbose = $false
  }

  $File2 = "install_arc_agent.sh"
  $sCopy2 = @{
    Source = $env:SrcPath + $File2 # SrcPath defined in vars.ps1
    Destination = "/tmp/arctemp/"
    VM = $VM
    LocalToGuest = $true
    GuestUser = $env:OSAdmin # OSAdmin defined in vars.ps1
    GuestPassword = $env:OSAdminPassword # OSAdminPassword defined in vars.ps1
    Verbose = $false
  }

  # Onboarding VM to Azure Arc
  Write-Host "Hold tight, I am onboarding $VMName Virtual Machine to Azure Arc..." -ForegroundColor Cyan
  Copy-VMGuestFile @sCopy1 -Force
  Copy-VMGuestFile @sCopy2 -Force
  #$Result = Invoke-VMScript -VM $VM -ScriptText "sudo chmod +x ./tmp/arctemp/install_arc_agent.sh && sudo ./tmp/arctemp/install_arc_agent.sh" -GuestUser $env:OSAdmin -GuestPassword $env:OSAdminPassword -ScriptType Bash
  #$Result = Invoke-VMScript -VM $VM -ScriptType bash -ScriptText "sudo bash /tmp/arctemp/install_arc_agent.sh" -GuestUser $env:OSAdmin -GuestPassword $env:OSAdminPassword
  #$Result = Invoke-VMScript -VM $VM -ScriptText "echo $env:OSAdminPassword | sudo -S bash /tmp/arctemp/install_arc_agent.sh" -GuestUser $env:OSAdmin -GuestPassword $env:OSAdminPassword -ScriptType Bash
  $Result = Invoke-VMScript -VM $VM -ScriptText "sudo bash /tmp/arctemp/install_arc_agent.sh" -GuestUser $env:OSAdmin -GuestPassword $env:OSAdminPassword -ScriptType Bash
  $ExitCode = $Result.ExitCode
  if ($ExitCode = "0") {
    Write-Host $VMName is now successfully onboarded to Azure Arc -ForegroundColor Green
  }
  Else {
    Write-Host $VMName returned exit code $ExitCode -ForegroundColor Red
  }

  # Cleaning garbage
  $Delete = Invoke-VMScript -VM $VM -ScriptText "rm -rf /tmp/arctemp/" -GuestUser $env:OSAdmin -GuestPassword $env:OSAdminPassword
}

Can you verify VMware Tools are running on the VM? It has Open VM Tools 
Can you please share the output on your PowerCLI version?
![image](https://user-images.githubusercontent.com/5447086/116629284-b44fee80-a905-11eb-84cf-7b2aa8bfb374.png)

**Comment by likamrat** [comment] 2021-04-30 13:45
The only difference I am seeing in the script is this line:
```shell
#$Result = Invoke-VMScript -VM $VM -ScriptText "echo $env:OSAdminPassword | sudo -S bash /tmp/arctemp/install_arc_agent.sh" -GuestUser $env:OSAdmin -GuestPassword $env:OSAdminPassword -ScriptType Bash
```
As I said, I don't see a need to change this. 

Since the Jumpstart automation was working for you on an Ubuntu machine and I wasn't able to reproduce the issue on both Ubuntu and CentOS, I will assume it is a local issue with your environment.

**Comment by likamrat** [comment] 2021-05-07 17:35
Closing this for now

**Closed by likamrat** 2021-05-07 17:35 UTC
Labels: arc_servers, bug
