### ISSUE TITLE
Getting error while installing Azure Key Vault Secrets Provider extension on HCI Arc enabled Cluster

### ISSUE THREAD

**Issue by mabhavsar** [microsoft/azure_arc#1587] opened 2023-01-04 14:12 UTC
**Is your issue related to a Jumpstart scenario, ArcBox, or HCIBox?**
https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_k8s/day2/cluster_api/cluster_api_keyvault_extension/#create-azure-key-vault-extensions-instance

**Create Azure Key Vault extensions instance step is failing.**

**Describe the bug**

Facing issues while installing AKV extension on arc enabled AKS cluster.
Error message as: (ExtensionOperationFailed) The extension operation failed with the following error:  Error: [Failed to setup Helm client during helm chart upgrade : err [mcr.microsoft.com/oss/azure/secrets-store/preview/provider-azure-arc:1.4.0: not found]] occurred while doing the operation : [Installing the extension] on the config.Code: ExtensionOperationFailed
Message: The extension operation failed with the following error:  Error: [Failed to setup Helm client during helm chart upgrade : err [mcr.microsoft.com/oss/azure/secrets-store/preview/provider-azure-arc:1.4.0: not found]] occurred while doing the operation : [Installing the extension] on the config.

**To Reproduce**

{    "status": "Failed",    "error": {        "code": "ExtensionOperationFailed",        "message": "The extension operation failed with the following error:  Error: [Failed to setup Helm client during helm chart upgrade : err [mcr.microsoft.com/oss/azure/secrets-store/stable/provider-azure-arc:1.4.0: not found]] occurred while doing the operation : [Installing the extension] on the config."    }}

**Expected behavior**

Key Vault extension should get deployed successfully. I have tried through AZ CLI . Same error.  Tried by installing helm3 
echo "Installing Helm 3"
curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
chmod 700 get_helm.sh
./get_helm.sh

Reference Link: https://github.com/microsoft/azure_arc/blob/main/azure_arc_k8s_jumpstart/cluster_api/capi_keyvault_extension/capi_keyvault_k8s_extension.sh

**Environment summary**

**Have you looked at the Troubleshooting and Logs section?**

**Screenshots**

**Additional context**

**Comment by likamrat** [comment] 2023-01-04 19:08
@mabhavsar following an investigation with @nilekhc, this is related to an [upstream issue](https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues/1054) with the extension. Until this will get fixed, I will be pushing a PR to pindown the extension to the previous version.

**Comment by likamrat** [comment] 2023-01-04 23:10
@mabhavsar PR is now merged but I am keeping the issue open for now until @niachary  will fix the extension upstream issue.

**Comment by mabhavsar** [comment] 2023-01-09 06:30
I am able to install KeyVault extension on an existing cluster. Thank you, team, for the quick fix.

**Comment by mabhavsar** [comment] 2023-01-09 06:31
Reopen to track until @nilekhc will fix the extension upstream issue.

**Comment by nilekhc** [comment] 2023-01-09 19:04
@mabhavsar @likamrat The issue is now resolved.

**Comment by likamrat** [comment] 2023-01-09 21:58
@nilekhc confirming the latest extension version works.

**Closed** 2023-01-09 21:57 UTC
Labels: bug, arc_k8s, pinned, upstream related
