### ISSUE TITLE
App Service (Container) ARM Template:  AppServicesLoginScript stuck waiting for log processor

### ISSUE THREAD

**Issue by larryclaman** [microsoft/azure_arc#1320] opened 2022-08-10 21:33 UTC
**Jumpstart scenario or ArcBox flavor which you are working on.**

https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_app_svc/cluster_api/capi_azure/apps_service_arm_template/#architecture-in-a-nutshell
**Describe the bug.**

After deploying the CAPI cluster, I logged into client and waited for the AppServicesLoginScript to execute.  It got stuck at "Waiting for log-processor to become available. Hold tight, this might take a few minutes..."

looking at the code, I see the lines in question are:
```
Do {
   Write-Host "Waiting for log-processor to become available. Hold tight, this might take a few minutes..."
   Start-Sleep -Seconds 15
   $logProcessorStatus = $(if(kubectl describe daemonset ($extensionName + "-k8se-log-processor") -n appservices | Select-String "Pods Status:  4 Running" -Quiet){"Ready!"}Else{"Nope"})
   } while ($logProcessorStatus -eq "Nope")

```
From another window, I ran:
```
 kubectl describe daemonset arc-app-services-k8se-log-processor    -n appservices
[...]
Pods Status:  6 Running / 0 Waiting / 0 Succeeded / 0 Failed
```

So it appears the cluster is trying to deploy the daemonset across 6 modes, but the script is hard-coded looking for 4 nodes.

**To Reproduce.**

**Expected behavior.**

**Environment summary.**

**Screenshots.**

**Additional context.**

**Comment by likamrat** [comment] 2022-08-11 15:34
Thank you @larryclaman. I think the issue is because we bumped the number of control plane nodes to 3 which adds two more pods to the mix. Let me test and push a PR!

**Comment by likamrat** [comment] 2022-08-29 14:06
@larryclaman I wanted to update you that we found a bug in ARM (outside of the Jumpstart) which we are working on. Once I will have validation, I will push a PR to fix this issue.

**Comment by likamrat** [comment] 2022-09-12 21:49
@larryclaman can you please test? fix has been pushed internally for Azure Functions and for the Jumpstart automation.

**Closed** 2022-09-12 21:48 UTC
Labels: bug, arc_app_svc
