### ISSUE TITLE
The azuredeploy.json was giving errors on the name of network interface, public IP address and DNS label prefix

### ISSUE THREAD

**Issue by msftjonw** [microsoft/azure_arc#434] opened 2021-03-08 20:51 UTC
**Scenario which you are working on**
A link to the Jumpstart scenario you are working on.
https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_servers/azure/azure_arm_template_linux/#deployment

**Describe the bug**
When using the provided script 

"az group create --name <Name of the Azure resource group> --location <Azure region> --tags "Project=jumpstart_azure_arc_servers"
az deployment group create \
--resource-group <Name of the Azure resource group> \
--name <The name of this deployment> \
--template-uri https://raw.githubusercontent.com/microsoft/azure_arc/main/azure_arc_servers_jumpstart/azure/linux/arm_template/azuredeploy.json \
--parameters <The *azuredeploy.parameters.json* parameters file location>"

I got naming errors on both network interface and public IP address. When I hardcoded the name with the same naming convention, the error went away. However, another similar issue comes with DNS label prefix.

**To Reproduce**
1. Go to https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_servers/azure/azure_arm_template_linux/#deployment
2. Execute the script in whatever environment
3. The naming errors come in the response
4. Did not save the error message as I eventually took a workaround

**Expected behavior**
The provided script would just create an Azure Linux VM and have connected to Azure Arc

**Screenshots**

**Additional context**

**Comment by lanicolas** [comment] 2021-03-09 17:36
Hi @msftjonw 

Do you have any idea of the error message? or what was it about? could it be it was not a unique name or had special characters?

**Comment by lanicolas** [comment] 2021-03-18 10:02
Closing the issue for now as we cannot reproduce this and do not have the error or inputs used. Please, if you encounter this problem again feel free to open it again.

**Closed by lanicolas** 2021-03-18 10:02 UTC
Labels: bug
