### ISSUE TITLE
Jumpstart ArcBox - Overview

### ISSUE THREAD

**Issue by ekramyelnaggar** [microsoft/azure_arc#907] opened 2021-12-28 10:48 UTC
I'm trying to deploy the Azure ArcBox template from here : https://azurearcjumpstart.io/azure_jumpstart_arcbox/

But it is always failing at the point of implementing custom script as VM extension to the 2 Linux machines.

I tried to deploy it to North Europe region , then to East US region >> but same errors occured.

I'm afraid the error messages are not descriptive enough to spot the root cause.
![1](https://user-images.githubusercontent.com/18163885/147558651-88d2fc20-0b28-4161-bb7c-facd9514cda6.jpg)
![2](https://user-images.githubusercontent.com/18163885/147558656-cb74be84-02f8-4e0b-aad2-04d8cbba0101.jpg)

Screenshots attached for more info.

**Comment by DCMattyG** [comment] 2021-12-28 17:54
Hi @ekramyelnaggar, I'm able to reproduce this issue when the Service Principal is *not* assigned as a contributor on the target subscription. Please make sure you're following the prerequisites which can be found here:

https://azurearcjumpstart.io/azure_jumpstart_arcbox/#prerequisites

Verify that the proper IAM role is assigned, and let me know the results. Happy to assist further if your issue continues after verifying the permissions. Thanks!

**Comment by likamrat** [comment] 2022-01-31 14:21
Due to the release of [ArcBox 2.0](https://aka.ms/JumpstartArcBox) I will go ahead and close this for now. Please comment if further assistance is required.

**Closed by likamrat** 2022-01-31 14:21 UTC
Labels: triage
