### ISSUE TITLE
 Azure Arc enabled data services for EKS : logon script does not end

### ISSUE THREAD

**Issue by dineshkvp** [microsoft/azure_arc#711] opened 2021-08-06 12:47 UTC
https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_data/eks/eks_mssql_mi/

I am trying to setup Amazon Elastic Kubernetes Service and SQL Managed Instance using Terraform through the referenced jump start tutorial (azure_arc\azure_arc_data_jumpstart\eks\mssql_mi\terraform)

I could successfully provision the environment through Terraform scripts running on Ubuntu. When i login to Windows Server Client instance for the first time, the logon script runs for ever. After waiting hours together it doesnt finish. Please find the screen shot below

![error1](https://user-images.githubusercontent.com/5206595/128512494-6c3fce7e-7ad7-42b5-91a2-3e5711654435.png)
![error2](https://user-images.githubusercontent.com/5206595/128512505-7d5d11d4-cfad-4167-93e3-900fd3b412bc.png)

**Comment by mdrakiburrahman** [comment] 2021-08-06 12:55
Hi @dineshkvp - thanks for bringing this to our attention.

Could you please share two artifacts:
* Logs from bootstrapper pod: `kubectl logs bootstrapper-4cgxr -n arc`: [example](https://kubernetes.io/docs/reference/kubectl/cheatsheet/#interacting-with-running-pods)
* Run describe command against pod for events `kubectl describe pod bootstrapper-4cgxr -n arc`

**Comment by dineshkvp** [comment] 2021-08-06 13:14
@mdrakiburrahman  I use the latest version cloned yesterday. Please find below the details you asked for
![error1](https://user-images.githubusercontent.com/5206595/128515637-105800c4-0179-475f-b954-94a88ebeda70.png)
![error2](https://user-images.githubusercontent.com/5206595/128515657-9c592e06-8b35-46de-8730-9baf2d916bb7.png)

**Comment by mdrakiburrahman** [comment] 2021-08-06 16:10
@dineshkvp I performed the EKS deployment now and was not able to reproduce the issue.

It seems your environment is going into a loop at [this line](https://github.com/microsoft/azure_arc/blob/5f0c529e899ba22617bf63ec81baa15e2636a432/azure_arc_data_jumpstart/eks/terraform/artifacts/DataServicesLogonScript.ps1#L180) after the Data Controller ARM deployment is done - but the deployment may have failed for some reason (e.g. permissions).

Could you go into the "Deployments" tab and check the status of the dataController deployment?
![image](https://user-images.githubusercontent.com/46581776/128539829-60d2f5aa-d3ea-4d17-a6eb-d324ec411be4.png)

You can drill in deeper by clicking the name above:
![image](https://user-images.githubusercontent.com/46581776/128539949-0c82ee65-a7d0-4210-aeb4-207e3d8fad2b.png)

If you see any errors in your view of the above, please share the details here for us to help.

**Comment by dineshkvp** [comment] 2021-08-07 07:19
@mdrakiburrahman  thanks for the input. I get the below error for data controller deployment.

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"Forbidden","message":"secrets \"controller-login-secret\" is forbidden: User \"581ce62d-cf79-475e-92a1-4d9794bb2353\" cannot get resource \"secrets\" in API group \"\" in the namespace \"arc\""}]}

The service principal is having contributor rights. What additional permissions should i grant

**Comment by mdrakiburrahman** [comment] 2021-08-07 19:05
Hi @dineshkvp,

Could you please attempt the following:
1. Assign the Service Principal `Monitoring Metrics Publisher` on the Azure Subscription [instructions here](https://docs.microsoft.com/en-us/azure/azure-arc/data/upload-metrics-and-logs-to-azure-monitor?pivots=client-operating-system-macos-and-linux#assign-roles-to-the-service-principal), in addition to keeping `Contributor`
2. Clean up your existing Terraform deployment and attempt a net new deployment with this permission
3. If you find the script reaches the same step after deploying the bootstrapper pod, please run `kubectl describe secret controller-login-secret -n arc` - and let us know if you see the secret.

Additionally, in your Azure Subscription, have you had success in deploying a scenario on an Azure K8s Cluster (e.g. [AKS](https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_data/aks/aks_mssql_mi_arm_template/), [Microk8s](https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_data/microk8s/azure/arm_template/mssql_mi/)) with the existing Service Principal? Or is EKS the first scenario you are trying?

**Comment by dineshkvp** [comment] 2021-08-08 14:28
@mdrakiburrahman  Even after granting the service principal mentioned permission script reaches the same state. When i run
kubectl describe secret controller-login-secret -n arc

i get the below error. I have not tried deploying Azure K8s Cluster with this service principal, and EKS is the first scenario i am trying
![error1](https://user-images.githubusercontent.com/5206595/128635478-def22d1f-e454-4da6-934d-4161b5f7b53c.png)

**Comment by mdrakiburrahman** [comment] 2021-08-08 15:34
@dineshkvp - there's a very similar error to what you're facing listed in the Arc Troubleshooting guide [here](https://docs.microsoft.com/en-us/azure/azure-arc/kubernetes/troubleshooting#insufficient-cluster-permissions):
```
Error: list: failed to list: secrets is forbidden: User "myuser" cannot list resource "secrets" in API group "" at the cluster scope.

The user connecting the cluster to Azure Arc should have cluster-admin role assigned to them on the cluster.
```

This seems related AWS IAM Role that was used to set up the EKS cluster, which is used to obtain the `kubeconfig` from EKS in the scenario via AWS IAM auth. The fact that you're not able to see the secret (and the secret may not have been created in the first place) implies that the role that generated the kubeconfig may not have `cluster-admin` - as the above docs state is a pre-req for Arc.

Are you running your scenario in an AWS account that is limited to not allows users have cluster-admin privileges for example? Tagging @likamrat for any AWS specifics.

**Comment by mdrakiburrahman** [comment] 2021-08-10 10:38
@dineshkvp as this behavior is not related to the AWS environment permissions where EKS resides, as opposed to settings on Jumpstart and/or Azure side, I am closing this issue. Feel free to reopen if you need additional assistance.

**Closed by mdrakiburrahman** 2021-08-10 10:38 UTC
Labels: bug

**Comment by dineshkvp** [comment] 2021-08-12 05:24
@mdrakiburrahman Do you mean it is because of a permission issue with respect to my Azure service principal
